server:
  port: 8080

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1 # This removes first prefix in the path from the URL before forwarding. No context path for downstream services.
      routes:
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patients/**
        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctors/**
        - id: appointment-service
          uri: lb://APPOINTMENT-SERVICE
          predicates:
            - Path=/appointments/**
          
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, metrics

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger - %msg%n"
