server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patients/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
